name: Build APK (Expo EAS)

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install dependencies
        run: npm ci

      - name: Run expo prebuild
        run: |
          npx expo prebuild --clean
          # Pastikan autolinking berhasil dengan memeriksa settings.gradle
          if [ -f "android/settings.gradle" ]; then
            echo "✅ Prebuild berhasil - folder android dibuat"
          else
            echo "❌ Prebuild gagal - folder android tidak dibuat"
            exit 1
          fi

      - name: Build APK with EAS
        run: |
          eas build --platform android --non-interactive --profile production --json > build-output.json
          BUILD_STATUS=$(jq -r '.[0].status' build-output.json)
          DOWNLOAD_URL=$(jq -r '.[0].artifacts.buildUrl' build-output.json)
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
          if [ "$BUILD_STATUS" != "finished" ]; then
            echo "Build failed with status: $BUILD_STATUS"
            cat build-output.json
            exit 1
          fi
        env:
          EXPO_TOKEN: ${{ secrets.TEST }}

      - name: Download APK from Expo
        run: |
          mkdir -p build-apk
          curl -L "$DOWNLOAD_URL" -o build-apk/app.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: konter-app-apk
          path: build-apk/app.apk
