name: Build APK (Expo EAS)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm ci

      - name: Build APK
        run: eas build --platform android --non-interactive

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: konter-app-apk
          path: ./build/**/*.apk
