name: Build APK (Expo EAS)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm ci

      - name: Build APK with EAS
        id: eas-build
        run: |
          # Jalankan build di Expo EAS
          eas build --platform android --non-interactive --json > build-output.json
          
          # Ambil URL download APK terakhir
          DOWNLOAD_URL=$(jq -r '.[0].artifacts.buildUrl' build-output.json)
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download APK from Expo
        run: |
          mkdir -p build-apk
          curl -L "$DOWNLOAD_URL" -o build-apk/app.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: konter-app-apk
          path: build-apk/app.apk
